# Generated by Django 4.2.4 on 2023-09-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_game_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
